services:
    app:
        build:
            context: .
        image: nextjs-dev
        ports:
            - '3000:3000'
            - '5555:5555'
        environment:
            NODE_ENV: development
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: /app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json

    postgres:
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=rep_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=abc
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
